server:
  port: 7878
  tomcat:
    relaxed-query-chars: '|,{,},[,],\'

spring:
  datasource:
    username: postgres #${DB_USERNAME}
    password: jooker131 #${DB_PASSWORD}
    url: jdbc:postgresql://localhost:5432/APIServer #${DB_JDBC_URL}
