spring:
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_HOST}:${SPRING_DATASOURCE_PORT}/"nameofDB"

files:
  root: ${FILES_ROOT}